services:
  squid:
    image: "ubuntu/squid:latest"

  squid-check:
    build:
      context: .
      dockerfile: dev.dockerfile
    depends_on:
      - squid
    command:
      - --proxy-address=squid:3128
      - --target-address=squid-check:8080
      - --log-level=debug
    ports:
      - "8080:8080"
