services:
  devcontainer:
    # Required for ptrace-based debuggers like C++, Go, and Rust
    cap_add:
      - SYS_PTRACE
    command: sleep infinity
    depends_on:
      - squid
    image: mcr.microsoft.com/devcontainers/base:trixie
    security_opt:
      - seccomp:unconfined
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - .:/workspace:cached
